---
language: perl
perl:
  - "5.30"
  - "5.26"

services:
  - docker

script:
  - docker build -t dokuwiki t/dokuwiki
  - docker run -d --name dokuwiki -p 127.0.0.1:8000:80 dokuwiki
  - docker ps -a
  - perl Makefile.PL
  - make install
  - git clone dokuwiki::http://127.0.0.1/ test-wiki
