<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: doku
 * Date: Sun, 23 Feb 2020 18:50:52 +0000
 */

$conf['title'] = 'test';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['remote'] = 1;
$conf['remoteuser'] = '';

// end auto-generated content
